# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 638)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Frame_mainwindow = QtWidgets.QFrame(self.centralwidget)
        self.Frame_mainwindow.setGeometry(QtCore.QRect(50, 50, 521, 461))
        self.Frame_mainwindow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_mainwindow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_mainwindow.setObjectName("Frame_mainwindow")
        self.SelectButton = QtWidgets.QPushButton(self.centralwidget)
        self.SelectButton.setGeometry(QtCore.QRect(610, 170, 101, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.SelectButton.setFont(font)
        self.SelectButton.setObjectName("SelectButton")
        self.PourAppearBut = QtWidgets.QPushButton(self.centralwidget)
        self.PourAppearBut.setGeometry(QtCore.QRect(610, 90, 101, 41))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(12)
        self.PourAppearBut.setFont(font)
        self.PourAppearBut.setObjectName("PourAppearBut")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.SelectButton.setText(_translate("MainWindow", "确认"))
        self.PourAppearBut.setText(_translate("MainWindow", "浇筑面貌"))
